spring.application.name=PackUp

spring.datasource.url=jdbc:mysql://localhost:3306/packUp
spring.datasource.username=root
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


spring.jpa.show-sql=true

spring.jpa.generate-ddl=true

spring.jpa.hibernate.ddl-auto=create-drop

server.web.error.include-message=always
server.web.error.include-stacktrace=always

greenapi.idInstance=710722748137
greenapi.apiTokenInstance=a03e2c25ce004246966b5df8fdc0760b292ac2b2b3d340fca7

greenapi.apiUrl=https://7107.api.greenapi.com

gemini.apiKey=AQ.Ab8RN6L8-rrMuyR1A4eoMqDGa4PTdJtMXSKP7EAqPTbLkNrUNg
gemini.apiUrl=https://generativelanguage.googleapis.com/v1beta/models/gemini-3.8-flash:generateContent