spring.application.name=Day4Exercise

spring.datasource.url=jdbc:mysql://localhost:3306/school
spring.datasource.username=root
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect



#// هل تبغى تشوف أوامر ال SQL ؟
spring.jpa.show-sql=true

# تبغاه تستخدم ال ddl ?
spring.jpa.generate-ddl=true

# هل كل مره نشغل السيرفر من جديد يسوي للي قبل دروب ؟ هنا حطينا ايه لأن تونا بالبداية ولازم نغيّر كل شوي ، بعدين نخليها ابديت
spring.jpa.hibernate.ddl-auto=update
//create-drop
//update

# هنا لو صار في مشكلة هل تبغى رسالة الإيرور تظهر ؟
server.web.error.include-message=always
server.web.error.include-stacktrace=always


